import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Skeleton from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'
import { useState, useEffect, useCallback } from 'react'
import dynamic from 'next/dynamic'

// const Product = dynamic(() => import('../components/Products/Products'))
import Product from '../components/Products/Products'
const fetchProducts = async () => {
  const products = await fetch('https://dummyjson.com/products', { cache: "force-cache" })
    .then(res => res.json())
  return products
}


export default function Home() {
  const [loading, setLoading] = useState(true)
  useEffect(() => {
    setLoading(false)
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <Product />
        </>
      </main>

    </div>
  )
}
